version: '3.3'

services:
  app:
    container_name: 'tesApp'
    build: .
    volumes :
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8090:3030"
    stdin_open: true

    environment:
      - PORT=3030
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DBNAME=todo4
    command: npm start
 
volumes:
  node_modules: